import Head from "next/head";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Football blogs - Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Football blogs</h1>
      </main>
    </div>
  );
}
