import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { fetchCategories } from "../http";
import { ICollectionResponse, ICategory } from "../types";
import { AxiosResponse } from "axios";
import Tabs from "../components/Tabs";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
}

const Home: NextPage<IPropTypes> = ({ categories }) => {
  console.log("categories", categories);
  return (
    <div>
      <Head>
        <title>Football blogs - Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories= {categories.items}/>
      <main>
        <h1>Welcome to Football blogs</h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  console.log("categories", categories);
  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
